[2023-03-06T23:31:14.575+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.create_table manual__2023-03-06T23:30:14.231430+00:00 [queued]>
[2023-03-06T23:31:14.663+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.create_table manual__2023-03-06T23:30:14.231430+00:00 [queued]>
[2023-03-06T23:31:14.678+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T23:31:14.694+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-06T23:31:14.696+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T23:31:14.874+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_table> on 2023-03-06 23:30:14.231430+00:00
[2023-03-06T23:31:14.903+0000] {standard_task_runner.py:55} INFO - Started process 152 to run task
[2023-03-06T23:31:14.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_second_webscrape', 'create_table', 'manual__2023-03-06T23:30:14.231430+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmps4rcrvds']
[2023-03-06T23:31:14.940+0000] {standard_task_runner.py:83} INFO - Job 125: Subtask create_table
[2023-03-06T23:31:15.197+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_second_webscrape.create_table manual__2023-03-06T23:30:14.231430+00:00 [running]> on host 12a6d3b9daec
[2023-03-06T23:31:15.444+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_second_webscrape
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T23:30:14.231430+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-06T23:30:14.231430+00:00
[2023-03-06T23:31:15.461+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_load.py", line 76, in create_table
    source_format=bigquery.SourceFormat.CVS,
AttributeError: type object 'SourceFormat' has no attribute 'CVS'
[2023-03-06T23:31:15.505+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_second_webscrape, task_id=create_table, execution_date=20230306T233014, start_date=20230306T233114, end_date=20230306T233115
[2023-03-06T23:31:15.551+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 125 for task create_table (type object 'SourceFormat' has no attribute 'CVS'; 152)
[2023-03-06T23:31:15.626+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-06T23:31:15.679+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
