[2023-03-07T23:54:25.733+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.google_drive_upload manual__2023-03-07T23:47:42.922440+00:00 [queued]>
[2023-03-07T23:54:25.788+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.google_drive_upload manual__2023-03-07T23:47:42.922440+00:00 [queued]>
[2023-03-07T23:54:25.791+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T23:54:25.795+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-07T23:54:25.798+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T23:54:25.911+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonVirtualenvOperator): google_drive_upload> on 2023-03-07 23:47:42.922440+00:00
[2023-03-07T23:54:25.958+0000] {standard_task_runner.py:55} INFO - Started process 703 to run task
[2023-03-07T23:54:26.000+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_second_webscrape', 'google_drive_upload', 'manual__2023-03-07T23:47:42.922440+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpnlweg6g1']
[2023-03-07T23:54:26.014+0000] {standard_task_runner.py:83} INFO - Job 180: Subtask google_drive_upload
[2023-03-07T23:54:26.722+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_second_webscrape.google_drive_upload manual__2023-03-07T23:47:42.922440+00:00 [running]> on host cd114ba8c1f8
[2023-03-07T23:54:27.559+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_second_webscrape
AIRFLOW_CTX_TASK_ID=google_drive_upload
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T23:47:42.922440+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-07T23:47:42.922440+00:00
[2023-03-07T23:54:27.622+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv16ee26te --system-site-packages
[2023-03-07T23:54:27.848+0000] {process_utils.py:183} INFO - Output:
[2023-03-07T23:54:32.059+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 1164ms
[2023-03-07T23:54:32.063+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venv16ee26te, clear=False, no_vcs_ignore=False, global=True)
[2023-03-07T23:54:32.068+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-03-07T23:54:32.072+0000] {process_utils.py:187} INFO -     added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
[2023-03-07T23:54:32.076+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-03-07T23:54:32.130+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv16ee26te/bin/pip install -r /tmp/venv16ee26te/requirements.txt
[2023-03-07T23:54:32.198+0000] {process_utils.py:183} INFO - Output:
[2023-03-07T23:54:38.670+0000] {process_utils.py:187} INFO - Collecting selenium
[2023-03-07T23:54:38.730+0000] {process_utils.py:187} INFO -   Using cached selenium-4.8.2-py3-none-any.whl (6.9 MB)
[2023-03-07T23:54:38.844+0000] {process_utils.py:187} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 2)) (1.3.5)
[2023-03-07T23:54:38.992+0000] {process_utils.py:187} INFO - Collecting gcsfs
[2023-03-07T23:54:38.999+0000] {process_utils.py:187} INFO -   Using cached gcsfs-2023.1.0-py2.py3-none-any.whl (26 kB)
[2023-03-07T23:54:39.010+0000] {process_utils.py:187} INFO - Requirement already satisfied: fsspec in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 4)) (2022.11.0)
[2023-03-07T23:54:39.014+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-storage in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 5)) (2.7.0)
[2023-03-07T23:54:39.020+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigquery in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 6)) (2.34.4)
[2023-03-07T23:54:39.025+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 7)) (2.16.0)
[2023-03-07T23:54:39.029+0000] {process_utils.py:187} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 8)) (4.11.1)
[2023-03-07T23:54:39.032+0000] {process_utils.py:187} INFO - Requirement already satisfied: lxml in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 9)) (4.9.2)
[2023-03-07T23:54:39.115+0000] {process_utils.py:187} INFO - Collecting html5lib
[2023-03-07T23:54:39.128+0000] {process_utils.py:187} INFO -   Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
[2023-03-07T23:54:39.138+0000] {process_utils.py:187} INFO - Requirement already satisfied: pytz in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 11)) (2022.7.1)
[2023-03-07T23:54:39.201+0000] {process_utils.py:187} INFO - Collecting tzwhere
[2023-03-07T23:54:39.205+0000] {process_utils.py:187} INFO -   Using cached tzwhere-3.0.3-py3-none-any.whl
[2023-03-07T23:54:39.221+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-google in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 13)) (8.8.0)
[2023-03-07T23:54:39.226+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***[google] in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venv16ee26te/requirements.txt (line 14)) (2.5.1)
[2023-03-07T23:54:39.322+0000] {process_utils.py:187} INFO - Collecting openai
[2023-03-07T23:54:39.330+0000] {process_utils.py:187} INFO -   Using cached openai-0.27.0-py3-none-any.whl (70 kB)
[2023-03-07T23:54:39.404+0000] {process_utils.py:187} INFO - Collecting pydrive
[2023-03-07T23:54:39.411+0000] {process_utils.py:187} INFO -   Using cached PyDrive-1.3.1-py3-none-any.whl
[2023-03-07T23:54:39.501+0000] {process_utils.py:187} INFO - Collecting trio-websocket~=0.9
[2023-03-07T23:54:39.511+0000] {process_utils.py:187} INFO -   Using cached trio_websocket-0.9.2-py3-none-any.whl (16 kB)
[2023-03-07T23:54:39.523+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2021.10.8 in /home/***/.local/lib/python3.7/site-packages (from selenium->-r /tmp/venv16ee26te/requirements.txt (line 1)) (2022.12.7)
[2023-03-07T23:54:39.610+0000] {process_utils.py:187} INFO - Collecting trio~=0.17
[2023-03-07T23:54:39.618+0000] {process_utils.py:187} INFO -   Using cached trio-0.22.0-py3-none-any.whl (384 kB)
[2023-03-07T23:54:39.637+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3[socks]~=1.26 in /home/***/.local/lib/python3.7/site-packages (from selenium->-r /tmp/venv16ee26te/requirements.txt (line 1)) (1.26.14)
[2023-03-07T23:54:39.684+0000] {process_utils.py:187} INFO - Requirement already satisfied: python-dateutil>=2.7.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r /tmp/venv16ee26te/requirements.txt (line 2)) (2.8.2)
[2023-03-07T23:54:39.691+0000] {process_utils.py:187} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r /tmp/venv16ee26te/requirements.txt (line 2)) (1.21.1)
[2023-03-07T23:54:39.724+0000] {process_utils.py:187} INFO - Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (3.8.3)
[2023-03-07T23:54:39.891+0000] {process_utils.py:187} INFO - Collecting fsspec
[2023-03-07T23:54:39.900+0000] {process_utils.py:187} INFO -   Using cached fsspec-2023.1.0-py3-none-any.whl (143 kB)
[2023-03-07T23:54:39.915+0000] {process_utils.py:187} INFO - Requirement already satisfied: decorator>4.1.2 in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (5.1.1)
[2023-03-07T23:54:39.919+0000] {process_utils.py:187} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (2.28.2)
[2023-03-07T23:54:39.922+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth-oauthlib in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (0.8.0)
[2023-03-07T23:54:40.096+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-resumable-media>=2.3.2 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venv16ee26te/requirements.txt (line 5)) (2.4.0)
[2023-03-07T23:54:40.106+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venv16ee26te/requirements.txt (line 5)) (2.8.2)
[2023-03-07T23:54:40.111+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venv16ee26te/requirements.txt (line 5)) (2.3.2)
[2023-03-07T23:54:40.316+0000] {process_utils.py:187} INFO - Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venv16ee26te/requirements.txt (line 6)) (1.19.6)
[2023-03-07T23:54:40.327+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venv16ee26te/requirements.txt (line 6)) (1.51.1)
[2023-03-07T23:54:40.340+0000] {process_utils.py:187} INFO - Requirement already satisfied: protobuf<4.0.0dev,>=3.12.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venv16ee26te/requirements.txt (line 6)) (3.20.0)
[2023-03-07T23:54:40.348+0000] {process_utils.py:187} INFO - Requirement already satisfied: packaging<22.0dev,>=14.3 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venv16ee26te/requirements.txt (line 6)) (21.3)
[2023-03-07T23:54:40.474+0000] {process_utils.py:187} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venv16ee26te/requirements.txt (line 7)) (4.2.2)
[2023-03-07T23:54:40.477+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venv16ee26te/requirements.txt (line 7)) (0.2.8)
[2023-03-07T23:54:40.482+0000] {process_utils.py:187} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venv16ee26te/requirements.txt (line 7)) (4.9)
[2023-03-07T23:54:40.491+0000] {process_utils.py:187} INFO - Requirement already satisfied: six>=1.9.0 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venv16ee26te/requirements.txt (line 7)) (1.16.0)
[2023-03-07T23:54:40.504+0000] {process_utils.py:187} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.7/site-packages (from beautifulsoup4->-r /tmp/venv16ee26te/requirements.txt (line 8)) (2.3.2.post1)
[2023-03-07T23:54:40.630+0000] {process_utils.py:187} INFO - Collecting webencodings
[2023-03-07T23:54:40.640+0000] {process_utils.py:187} INFO -   Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
[2023-03-07T23:54:41.274+0000] {process_utils.py:187} INFO - Collecting shapely
[2023-03-07T23:54:41.300+0000] {process_utils.py:187} INFO -   Using cached shapely-2.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
[2023-03-07T23:54:41.637+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-memcache>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.4.1)
[2023-03-07T23:54:41.645+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-tasks>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.10.1)
[2023-03-07T23:54:41.648+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataproc>=3.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (5.0.0)
[2023-03-07T23:54:41.656+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-translate<2.0.0,>=1.5.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.7.2)
[2023-03-07T23:54:41.663+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-texttospeech<2.0.0,>=0.4.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.0.3)
[2023-03-07T23:54:41.666+0000] {process_utils.py:187} INFO - Requirement already satisfied: pandas-gbq in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.17.9)
[2023-03-07T23:54:41.672+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.7.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.16.1)
[2023-03-07T23:54:41.676+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-container<3.0.0,>=2.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.11.1)
[2023-03-07T23:54:41.679+0000] {process_utils.py:187} INFO - Requirement already satisfied: looker-sdk>=22.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (22.20.0)
[2023-03-07T23:54:41.683+0000] {process_utils.py:187} INFO - Requirement already satisfied: json-merge-patch>=0.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.2)
[2023-03-07T23:54:41.695+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-automl>=2.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.8.0)
[2023-03-07T23:54:41.705+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-common-sql>=1.3.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.3.3)
[2023-03-07T23:54:41.712+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-orchestration-***<2.0.0,>=1.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.4.1)
[2023-03-07T23:54:41.718+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-os-login>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.7.1)
[2023-03-07T23:54:41.723+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-storage in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (8.0.0)
[2023-03-07T23:54:41.727+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dlp<2.0.0,>=0.11.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.0.2)
[2023-03-07T23:54:41.732+0000] {process_utils.py:187} INFO - Requirement already satisfied: PyOpenSSL in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (22.1.0)
[2023-03-07T23:54:41.737+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataform>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.2.0)
[2023-03-07T23:54:41.743+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-monitoring>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.11.0)
[2023-03-07T23:54:41.747+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-workflows<2.0.0,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.7.1)
[2023-03-07T23:54:41.750+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-pubsub>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.13.5)
[2023-03-07T23:54:41.755+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataproc-metastore<2.0.0,>=1.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.6.0)
[2023-03-07T23:54:41.757+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-redis>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.9.0)
[2023-03-07T23:54:41.761+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth-httplib2>=0.0.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.1.0)
[2023-03-07T23:54:41.764+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-kms>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.12.0)
[2023-03-07T23:54:41.767+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-language<2.0.0,>=1.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.3.2)
[2023-03-07T23:54:41.771+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlalchemy-bigquery>=1.2.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.5.0)
[2023-03-07T23:54:41.774+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-api-python-client<2.0.0,>=1.6.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.12.11)
[2023-03-07T23:54:41.778+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigquery-datatransfer>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.7.0)
[2023-03-07T23:54:41.783+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigtable<2.0.0,>=1.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.7.3)
[2023-03-07T23:54:41.788+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-vision<2.0.0,>=0.35.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.0.2)
[2023-03-07T23:54:41.795+0000] {process_utils.py:187} INFO - Requirement already satisfied: httpx in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.23.3)
[2023-03-07T23:54:41.798+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-videointelligence<2.0.0,>=1.7.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.16.3)
[2023-03-07T23:54:41.801+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-bigquery>=6.1.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (6.2.0)
[2023-03-07T23:54:41.805+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-datacatalog>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.9.0)
[2023-03-07T23:54:41.808+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataplex>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.1.0)
[2023-03-07T23:54:41.811+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-ads>=15.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (18.0.0)
[2023-03-07T23:54:41.814+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpcio-gcp>=0.2.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.2.2)
[2023-03-07T23:54:41.817+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-secret-manager<2.0.0,>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.0.2)
[2023-03-07T23:54:41.820+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-auth>=4.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (4.1.5)
[2023-03-07T23:54:41.824+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-spanner<2.0.0,>=1.10.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.19.3)
[2023-03-07T23:54:41.829+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-logging>=2.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.2.1)
[2023-03-07T23:54:41.832+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-speech<2.0.0,>=0.36.3 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.3.4)
[2023-03-07T23:54:41.835+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-build>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.9.0)
[2023-03-07T23:54:41.840+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-compute<2.0.0,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.7.0)
[2023-03-07T23:54:41.843+0000] {process_utils.py:187} INFO - Requirement already satisfied: asgiref>=3.5.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.6.0)
[2023-03-07T23:55:00.179+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask<2.3,>=2.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.2.2)
[2023-03-07T23:55:00.190+0000] {process_utils.py:187} INFO - Requirement already satisfied: blinker in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.5)
[2023-03-07T23:55:00.192+0000] {process_utils.py:187} INFO - Requirement already satisfied: gunicorn>=20.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (20.1.0)
[2023-03-07T23:55:00.195+0000] {process_utils.py:187} INFO - Requirement already satisfied: rich>=12.4.4 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (13.1.0)
[2023-03-07T23:55:00.202+0000] {process_utils.py:187} INFO - Requirement already satisfied: tabulate>=0.7.5 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.9.0)
[2023-03-07T23:55:00.206+0000] {process_utils.py:187} INFO - Requirement already satisfied: graphviz>=0.12 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.20.1)
[2023-03-07T23:55:00.254+0000] {process_utils.py:187} INFO - Requirement already satisfied: markupsafe>=1.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.1.2)
[2023-03-07T23:55:00.257+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-sqlite in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.3.1)
[2023-03-07T23:55:00.261+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask-login>=0.6.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.6.2)
[2023-03-07T23:55:00.264+0000] {process_utils.py:187} INFO - Requirement already satisfied: cron-descriptor>=1.2.24 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.2.32)
[2023-03-07T23:55:00.284+0000] {process_utils.py:187} INFO - Requirement already satisfied: argcomplete>=1.10 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.0.0)
[2023-03-07T23:55:00.288+0000] {process_utils.py:187} INFO - Requirement already satisfied: typing-extensions>=4.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.4.0)
[2023-03-07T23:55:00.298+0000] {process_utils.py:187} INFO - Requirement already satisfied: jinja2>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.1.2)
[2023-03-07T23:55:00.304+0000] {process_utils.py:187} INFO - Requirement already satisfied: connexion[flask]>=2.10.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.14.1)
[2023-03-07T23:55:00.321+0000] {process_utils.py:187} INFO - Requirement already satisfied: pygments>=2.0.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.14.0)
[2023-03-07T23:55:00.328+0000] {process_utils.py:187} INFO - Requirement already satisfied: python-nvd3>=0.15.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.15.0)
[2023-03-07T23:55:00.340+0000] {process_utils.py:187} INFO - Requirement already satisfied: tenacity>=6.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (8.1.0)
[2023-03-07T23:55:00.344+0000] {process_utils.py:187} INFO - Requirement already satisfied: alembic<2.0,>=1.6.3 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.9.2)
[2023-03-07T23:55:00.356+0000] {process_utils.py:187} INFO - Requirement already satisfied: marshmallow-oneofschema>=2.0.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.0.1)
[2023-03-07T23:55:00.359+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask-wtf>=0.15 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.1.1)
[2023-03-07T23:55:00.363+0000] {process_utils.py:187} INFO - Requirement already satisfied: psutil>=4.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (5.9.4)
[2023-03-07T23:55:00.376+0000] {process_utils.py:187} INFO - Requirement already satisfied: mdit-py-plugins>=0.3.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.3.3)
[2023-03-07T23:55:00.378+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-imap in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.1.1)
[2023-03-07T23:55:00.380+0000] {process_utils.py:187} INFO - Requirement already satisfied: python-daemon>=2.2.4 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.3.2)
[2023-03-07T23:55:00.384+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-ftp in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.3.0)
[2023-03-07T23:55:00.387+0000] {process_utils.py:187} INFO - Requirement already satisfied: colorlog<5.0,>=4.0.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.8.0)
[2023-03-07T23:55:00.390+0000] {process_utils.py:187} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.2.0)
[2023-03-07T23:55:00.393+0000] {process_utils.py:187} INFO - Requirement already satisfied: attrs>=22.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (22.2.0)
[2023-03-07T23:55:00.398+0000] {process_utils.py:187} INFO - Requirement already satisfied: python-slugify>=5.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (7.0.0)
[2023-03-07T23:55:00.406+0000] {process_utils.py:187} INFO - Requirement already satisfied: importlib-resources>=5.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (5.10.2)
[2023-03-07T23:55:00.409+0000] {process_utils.py:187} INFO - Requirement already satisfied: pendulum>=2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.1.2)
[2023-03-07T23:55:00.413+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlalchemy<2.0,>=1.4 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.4.46)
[2023-03-07T23:55:00.416+0000] {process_utils.py:187} INFO - Requirement already satisfied: cattrs>=22.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (22.2.0)
[2023-03-07T23:55:00.421+0000] {process_utils.py:187} INFO - Requirement already satisfied: jsonschema>=3.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.17.3)
[2023-03-07T23:55:00.425+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask-appbuilder==4.1.4 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.1.4)
[2023-03-07T23:55:00.429+0000] {process_utils.py:187} INFO - Requirement already satisfied: setproctitle>=1.1.8 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.3.2)
[2023-03-07T23:55:00.433+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlalchemy-jsonfield>=1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.0.1.post0)
[2023-03-07T23:55:00.436+0000] {process_utils.py:187} INFO - Requirement already satisfied: markdown-it-py>=2.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.1.0)
[2023-03-07T23:55:00.439+0000] {process_utils.py:187} INFO - Requirement already satisfied: lockfile>=0.12.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.12.2)
[2023-03-07T23:55:00.443+0000] {process_utils.py:187} INFO - Requirement already satisfied: unicodecsv>=0.14.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.14.1)
[2023-03-07T23:55:00.448+0000] {process_utils.py:187} INFO - Requirement already satisfied: importlib-metadata>=1.7 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.13.0)
[2023-03-07T23:55:00.453+0000] {process_utils.py:187} INFO - Requirement already satisfied: pathspec~=0.9.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.9.0)
[2023-03-07T23:55:00.456+0000] {process_utils.py:187} INFO - Requirement already satisfied: croniter>=0.3.17 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.3.8)
[2023-03-07T23:55:00.461+0000] {process_utils.py:187} INFO - Requirement already satisfied: pluggy>=1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.0.0)
[2023-03-07T23:55:00.467+0000] {process_utils.py:187} INFO - Requirement already satisfied: markdown>=3.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.4.1)
[2023-03-07T23:55:00.470+0000] {process_utils.py:187} INFO - Requirement already satisfied: configupdater>=3.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.1.1)
[2023-03-07T23:55:00.474+0000] {process_utils.py:187} INFO - Requirement already satisfied: lazy-object-proxy in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.9.0)
[2023-03-07T23:55:00.476+0000] {process_utils.py:187} INFO - Requirement already satisfied: werkzeug>=2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.2.2)
[2023-03-07T23:55:00.480+0000] {process_utils.py:187} INFO - Requirement already satisfied: linkify-it-py>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.0.0)
[2023-03-07T23:55:00.484+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask-session>=0.4.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.4.0)
[2023-03-07T23:55:00.488+0000] {process_utils.py:187} INFO - Requirement already satisfied: dill>=0.2.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.3.1.1)
[2023-03-07T23:55:00.493+0000] {process_utils.py:187} INFO - Requirement already satisfied: cached-property>=1.5.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.5.2)
[2023-03-07T23:55:00.500+0000] {process_utils.py:187} INFO - Requirement already satisfied: deprecated>=1.2.13 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.2.13)
[2023-03-07T23:55:00.513+0000] {process_utils.py:187} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.1.2)
[2023-03-07T23:55:00.533+0000] {process_utils.py:187} INFO - Requirement already satisfied: flask-caching>=1.5.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.0.2)
[2023-03-07T23:55:00.536+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyjwt>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.6.0)
[2023-03-07T23:55:00.541+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-http in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.1.1)
[2023-03-07T23:55:00.551+0000] {process_utils.py:187} INFO - Requirement already satisfied: cryptography>=0.9.3 in /home/***/.local/lib/python3.7/site-packages (from apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (38.0.4)
[2023-03-07T23:55:00.655+0000] {process_utils.py:187} INFO - Requirement already satisfied: Flask-JWT-Extended<5.0.0,>=4.0.0 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (4.4.4)
[2023-03-07T23:55:00.658+0000] {process_utils.py:187} INFO - Requirement already satisfied: colorama<1,>=0.3.9 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.4.6)
[2023-03-07T23:55:00.664+0000] {process_utils.py:187} INFO - Requirement already satisfied: marshmallow-sqlalchemy<0.27.0,>=0.22.0 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.26.1)
[2023-03-07T23:55:00.668+0000] {process_utils.py:187} INFO - Requirement already satisfied: Flask-SQLAlchemy<3,>=2.4 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.5.1)
[2023-03-07T23:55:00.673+0000] {process_utils.py:187} INFO - Requirement already satisfied: marshmallow-enum<2,>=1.5.1 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.5.1)
[2023-03-07T23:55:00.677+0000] {process_utils.py:187} INFO - Requirement already satisfied: email-validator<2,>=1.0.5 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.3.0)
[2023-03-07T23:55:00.682+0000] {process_utils.py:187} INFO - Requirement already satisfied: prison<1.0.0,>=0.2.1 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.2.1)
[2023-03-07T23:55:00.687+0000] {process_utils.py:187} INFO - Requirement already satisfied: click<9,>=8 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (8.1.3)
[2023-03-07T23:55:00.698+0000] {process_utils.py:187} INFO - Requirement already satisfied: marshmallow<4,>=3 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.19.0)
[2023-03-07T23:55:00.704+0000] {process_utils.py:187} INFO - Requirement already satisfied: apispec[yaml]<4,>=3.3 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.3.2)
[2023-03-07T23:55:00.708+0000] {process_utils.py:187} INFO - Requirement already satisfied: Flask-Babel<3,>=1 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.0.0)
[2023-03-07T23:55:00.710+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlalchemy-utils<1,>=0.32.21 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.39.0)
[2023-03-07T23:55:00.712+0000] {process_utils.py:187} INFO - Requirement already satisfied: WTForms<4 in /home/***/.local/lib/python3.7/site-packages (from flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.0.1)
[2023-03-07T23:55:01.284+0000] {process_utils.py:187} INFO - Collecting tqdm
[2023-03-07T23:55:01.293+0000] {process_utils.py:187} INFO -   Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
[2023-03-07T23:55:01.471+0000] {process_utils.py:187} INFO - Collecting oauth2client>=4.0.0
[2023-03-07T23:55:01.477+0000] {process_utils.py:187} INFO -   Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
[2023-03-07T23:55:01.487+0000] {process_utils.py:187} INFO - Requirement already satisfied: PyYAML>=3.0 in /home/***/.local/lib/python3.7/site-packages (from pydrive->-r /tmp/venv16ee26te/requirements.txt (line 16)) (6.0)
[2023-03-07T23:55:01.566+0000] {process_utils.py:187} INFO - Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (2.1.1)
[2023-03-07T23:55:01.572+0000] {process_utils.py:187} INFO - Requirement already satisfied: yarl<2.0,>=1.0 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (1.8.2)
[2023-03-07T23:55:01.576+0000] {process_utils.py:187} INFO - Requirement already satisfied: frozenlist>=1.1.1 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (1.3.3)
[2023-03-07T23:55:01.579+0000] {process_utils.py:187} INFO - Requirement already satisfied: aiosignal>=1.1.2 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (1.3.1)
[2023-03-07T23:55:01.585+0000] {process_utils.py:187} INFO - Requirement already satisfied: multidict<7.0,>=4.5 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (6.0.4)
[2023-03-07T23:55:01.595+0000] {process_utils.py:187} INFO - Requirement already satisfied: asynctest==0.13.0 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (0.13.0)
[2023-03-07T23:55:01.602+0000] {process_utils.py:187} INFO - Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/***/.local/lib/python3.7/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (4.0.2)
[2023-03-07T23:55:01.671+0000] {process_utils.py:187} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.7/site-packages (from alembic<2.0,>=1.6.3->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.2.4)
[2023-03-07T23:55:01.746+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlparse>=0.4.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-common-sql>=1.3.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.4.3)
[2023-03-07T23:55:02.422+0000] {process_utils.py:187} INFO - Requirement already satisfied: exceptiongroup in /home/***/.local/lib/python3.7/site-packages (from cattrs>=22.1.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.1.0)
[2023-03-07T23:55:02.855+0000] {process_utils.py:187} INFO - Requirement already satisfied: inflection<0.6,>=0.3.1 in /home/***/.local/lib/python3.7/site-packages (from connexion[flask]>=2.10.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.5.1)
[2023-03-07T23:55:02.865+0000] {process_utils.py:187} INFO - Requirement already satisfied: clickclick<21,>=1.2 in /home/***/.local/lib/python3.7/site-packages (from connexion[flask]>=2.10.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (20.10.2)
[2023-03-07T23:55:03.120+0000] {process_utils.py:187} INFO - Requirement already satisfied: cffi>=1.12 in /home/***/.local/lib/python3.7/site-packages (from cryptography>=0.9.3->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.15.1)
[2023-03-07T23:55:03.312+0000] {process_utils.py:187} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.7/site-packages (from deprecated>=1.2.13->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.14.1)
[2023-03-07T23:55:03.474+0000] {process_utils.py:187} INFO - Requirement already satisfied: cachelib<0.10.0,>=0.9.0 in /home/***/.local/lib/python3.7/site-packages (from flask-caching>=1.5.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.9.0)
[2023-03-07T23:55:03.795+0000] {process_utils.py:187} INFO - Requirement already satisfied: backoff<3.0.0,>=1.0.0 in /home/***/.local/lib/python3.7/site-packages (from gcloud-aio-auth>=4.0.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.10.0)
[2023-03-07T23:55:03.821+0000] {process_utils.py:187} INFO - Requirement already satisfied: future<0.19.0,>=0.17.0 in /home/***/.local/lib/python3.7/site-packages (from gcloud-aio-auth>=4.0.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.18.3)
[2023-03-07T23:55:03.864+0000] {process_utils.py:187} INFO - Requirement already satisfied: chardet<4.1,>=2.0 in /home/***/.local/lib/python3.7/site-packages (from gcloud-aio-auth>=4.0.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (4.0.0)
[2023-03-07T23:55:04.343+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpcio-status<2.0.0,>=1.38.1 in /home/***/.local/lib/python3.7/site-packages (from google-ads>=15.1.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.48.2)
[2023-03-07T23:55:04.361+0000] {process_utils.py:187} INFO - Requirement already satisfied: setuptools>=40.3.0 in /tmp/venv16ee26te/lib/python3.7/site-packages (from google-ads>=15.1.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (65.6.3)
[2023-03-07T23:55:04.376+0000] {process_utils.py:187} INFO - Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.5.8 in /home/***/.local/lib/python3.7/site-packages (from google-ads>=15.1.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.56.4)
[2023-03-07T23:55:04.775+0000] {process_utils.py:187} INFO - Requirement already satisfied: httplib2<1dev,>=0.15.0 in /home/***/.local/lib/python3.7/site-packages (from google-api-python-client<2.0.0,>=1.6.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.20.4)
[2023-03-07T23:55:04.790+0000] {process_utils.py:187} INFO - Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from google-api-python-client<2.0.0,>=1.6.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.0.1)
[2023-03-07T23:55:05.061+0000] {process_utils.py:187} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.7/site-packages (from google-auth-oauthlib->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (1.3.1)
[2023-03-07T23:55:05.960+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-aiplatform<2.0.0,>=1.7.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.6.0)
[2023-03-07T23:55:06.234+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpc-google-iam-v1<0.13dev,>=0.12.3 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigtable<2.0.0,>=1.0.0->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.12.4)
[2023-03-07T23:55:08.586+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-appengine-logging<2.0.0dev,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-logging>=2.1.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.1.3)
[2023-03-07T23:55:08.614+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-audit-log<1.0.0dev,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-logging>=2.1.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.2.4)
[2023-03-07T23:55:12.105+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/***/.local/lib/python3.7/site-packages (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venv16ee26te/requirements.txt (line 5)) (1.5.0)
[2023-03-07T23:55:12.949+0000] {process_utils.py:187} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.7/site-packages (from importlib-metadata>=1.7->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (3.11.0)
[2023-03-07T23:55:13.743+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.2.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.19.3)
[2023-03-07T23:55:13.782+0000] {process_utils.py:187} INFO - Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/***/.local/lib/python3.7/site-packages (from jsonschema>=3.2.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.3.10)
[2023-03-07T23:55:14.063+0000] {process_utils.py:187} INFO - Requirement already satisfied: uc-micro-py in /home/***/.local/lib/python3.7/site-packages (from linkify-it-py>=2.0.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.0.1)
[2023-03-07T23:55:14.755+0000] {process_utils.py:187} INFO - Requirement already satisfied: mdurl~=0.1 in /home/***/.local/lib/python3.7/site-packages (from markdown-it-py>=2.1.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.1.2)
[2023-03-07T23:55:15.843+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyasn1>=0.1.7 in /home/***/.local/lib/python3.7/site-packages (from oauth2client>=4.0.0->pydrive->-r /tmp/venv16ee26te/requirements.txt (line 16)) (0.4.8)
[2023-03-07T23:55:15.967+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/***/.local/lib/python3.7/site-packages (from packaging<22.0dev,>=14.3->google-cloud-bigquery->-r /tmp/venv16ee26te/requirements.txt (line 6)) (3.0.9)
[2023-03-07T23:55:16.158+0000] {process_utils.py:187} INFO - Requirement already satisfied: pytzdata>=2020.1 in /home/***/.local/lib/python3.7/site-packages (from pendulum>=2.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2020.1)
[2023-03-07T23:55:16.981+0000] {process_utils.py:187} INFO - Requirement already satisfied: docutils in /home/***/.local/lib/python3.7/site-packages (from python-daemon>=2.2.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.19)
[2023-03-07T23:55:17.437+0000] {process_utils.py:187} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.7/site-packages (from python-slugify>=5.0->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (1.3)
[2023-03-07T23:55:17.737+0000] {process_utils.py:187} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.7/site-packages (from requests->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (3.4)
[2023-03-07T23:55:17.858+0000] {process_utils.py:187} INFO - Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/***/.local/lib/python3.7/site-packages (from rich>=12.4.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.9.1)
[2023-03-07T23:55:18.810+0000] {process_utils.py:187} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.7/site-packages (from sqlalchemy<2.0,>=1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.0.1)
[2023-03-07T23:55:18.978+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyarrow>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from sqlalchemy-bigquery>=1.2.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (9.0.0)
[2023-03-07T23:55:18.982+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigquery-storage<3.0.0dev,>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from sqlalchemy-bigquery>=1.2.1->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (2.14.1)
[2023-03-07T23:55:19.712+0000] {process_utils.py:187} INFO - Collecting async-generator>=1.9
[2023-03-07T23:55:19.732+0000] {process_utils.py:187} INFO -   Using cached async_generator-1.10-py3-none-any.whl (18 kB)
[2023-03-07T23:55:19.831+0000] {process_utils.py:187} INFO - Collecting outcome
[2023-03-07T23:55:19.837+0000] {process_utils.py:187} INFO -   Using cached outcome-1.2.0-py2.py3-none-any.whl (9.7 kB)
[2023-03-07T23:55:19.848+0000] {process_utils.py:187} INFO - Requirement already satisfied: sniffio in /home/***/.local/lib/python3.7/site-packages (from trio~=0.17->selenium->-r /tmp/venv16ee26te/requirements.txt (line 1)) (1.3.0)
[2023-03-07T23:55:19.850+0000] {process_utils.py:187} INFO - Requirement already satisfied: sortedcontainers in /home/***/.local/lib/python3.7/site-packages (from trio~=0.17->selenium->-r /tmp/venv16ee26te/requirements.txt (line 1)) (2.4.0)
[2023-03-07T23:55:20.127+0000] {process_utils.py:187} INFO - Collecting wsproto>=0.14
[2023-03-07T23:55:20.133+0000] {process_utils.py:187} INFO -   Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
[2023-03-07T23:55:20.776+0000] {process_utils.py:187} INFO - Collecting PySocks!=1.5.7,<2.0,>=1.5.6
[2023-03-07T23:55:20.782+0000] {process_utils.py:187} INFO -   Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
[2023-03-07T23:55:21.028+0000] {process_utils.py:187} INFO - Requirement already satisfied: requests-toolbelt in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-http->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (0.10.1)
[2023-03-07T23:55:21.576+0000] {process_utils.py:187} INFO - Requirement already satisfied: aiofiles<23.0.0,>=0.6.0 in /home/***/.local/lib/python3.7/site-packages (from gcloud-aio-storage->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (22.1.0)
[2023-03-07T23:55:21.753+0000] {process_utils.py:187} INFO - Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/***/.local/lib/python3.7/site-packages (from httpx->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.5.0)
[2023-03-07T23:55:21.759+0000] {process_utils.py:187} INFO - Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/***/.local/lib/python3.7/site-packages (from httpx->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.16.3)
[2023-03-07T23:55:22.394+0000] {process_utils.py:187} INFO - Requirement already satisfied: pydata-google-auth in /home/***/.local/lib/python3.7/site-packages (from pandas-gbq->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.5.0)
[2023-03-07T23:55:22.449+0000] {process_utils.py:187} INFO - Requirement already satisfied: db-dtypes<2.0.0,>=0.3.1 in /home/***/.local/lib/python3.7/site-packages (from pandas-gbq->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (1.0.5)
[2023-03-07T23:55:25.774+0000] {process_utils.py:187} INFO - Requirement already satisfied: pycparser in /home/***/.local/lib/python3.7/site-packages (from cffi>=1.12->cryptography>=0.9.3->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.21)
[2023-03-07T23:55:27.424+0000] {process_utils.py:187} INFO - Requirement already satisfied: dnspython>=1.15.0 in /home/***/.local/lib/python3.7/site-packages (from email-validator<2,>=1.0.5->flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.3.0)
[2023-03-07T23:55:28.224+0000] {process_utils.py:187} INFO - Requirement already satisfied: Babel>=2.3 in /home/***/.local/lib/python3.7/site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.1.4->apache-***[google]->-r /tmp/venv16ee26te/requirements.txt (line 14)) (2.11.0)
[2023-03-07T23:55:29.116+0000] {process_utils.py:187} INFO - WARNING: google-api-core 2.8.2 does not provide the extra 'grpcgcp'
[2023-03-07T23:55:31.338+0000] {process_utils.py:187} INFO - Requirement already satisfied: anyio<5.0,>=3.0 in /home/***/.local/lib/python3.7/site-packages (from httpcore<0.17.0,>=0.15.0->httpx->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (3.6.2)
[2023-03-07T23:55:31.358+0000] {process_utils.py:187} INFO - Requirement already satisfied: h11<0.15,>=0.13 in /home/***/.local/lib/python3.7/site-packages (from httpcore<0.17.0,>=0.15.0->httpx->apache-***-providers-google->-r /tmp/venv16ee26te/requirements.txt (line 13)) (0.14.0)
[2023-03-07T23:55:34.453+0000] {process_utils.py:187} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs->-r /tmp/venv16ee26te/requirements.txt (line 3)) (3.2.2)
[2023-03-07T23:55:41.059+0000] {process_utils.py:187} INFO - Installing collected packages: webencodings, tqdm, shapely, PySocks, outcome, html5lib, fsspec, async-generator, wsproto, tzwhere, trio, oauth2client, trio-websocket, openai, selenium, pydrive, gcsfs
[2023-03-07T23:55:42.328+0000] {process_utils.py:187} INFO -   Attempting uninstall: fsspec
[2023-03-07T23:55:42.339+0000] {process_utils.py:187} INFO -     Found existing installation: fsspec 2022.11.0
[2023-03-07T23:55:42.345+0000] {process_utils.py:187} INFO -     Not uninstalling fsspec at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv16ee26te
[2023-03-07T23:55:42.351+0000] {process_utils.py:187} INFO -     Can't uninstall 'fsspec'. No files were found to uninstall.
[2023-03-07T23:55:49.725+0000] {process_utils.py:187} INFO - Successfully installed PySocks-1.7.1 async-generator-1.10 fsspec-2023.1.0 gcsfs-2023.1.0 html5lib-1.1 oauth2client-4.1.3 openai-0.27.0 outcome-1.2.0 pydrive-1.3.1 selenium-4.8.2 shapely-2.0.1 tqdm-4.65.0 trio-0.22.0 trio-websocket-0.9.2 tzwhere-3.0.3 webencodings-0.5.1 wsproto-1.2.0
[2023-03-07T23:55:50.496+0000] {process_utils.py:187} INFO - 
[2023-03-07T23:55:50.499+0000] {process_utils.py:187} INFO - [notice] A new release of pip available: 22.3.1 -> 23.0.1
[2023-03-07T23:55:50.501+0000] {process_utils.py:187} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-03-07T23:55:51.318+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv16ee26te/bin/python /tmp/venv16ee26te/script.py /tmp/venv16ee26te/script.in /tmp/venv16ee26te/script.out /tmp/venv16ee26te/string_args.txt
[2023-03-07T23:55:51.421+0000] {process_utils.py:183} INFO - Output:
[2023-03-07T23:55:55.928+0000] {process_utils.py:187} INFO - Traceback (most recent call last):
[2023-03-07T23:55:55.931+0000] {process_utils.py:187} INFO -   File "/tmp/venv16ee26te/script.py", line 37, in <module>
[2023-03-07T23:55:55.934+0000] {process_utils.py:187} INFO -     res = google_drive_upload(*arg_dict["args"], **arg_dict["kwargs"])
[2023-03-07T23:55:55.939+0000] {process_utils.py:187} INFO -   File "/tmp/venv16ee26te/script.py", line 34, in google_drive_upload
[2023-03-07T23:55:55.942+0000] {process_utils.py:187} INFO -     file.SetContentFile(os.path.join(data_dir,config['bitcoin_consolidated']))
[2023-03-07T23:55:55.944+0000] {process_utils.py:187} INFO - NameError: name 'data_dir' is not defined
[2023-03-07T23:55:56.564+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 356, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 553, in execute_callable
    return self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 418, in _execute_python_callable_in_subprocess
    os.fspath(string_args_path),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 168, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 191, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv16ee26te/bin/python', '/tmp/venv16ee26te/script.py', '/tmp/venv16ee26te/script.in', '/tmp/venv16ee26te/script.out', '/tmp/venv16ee26te/string_args.txt']' returned non-zero exit status 1.
[2023-03-07T23:55:56.605+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_second_webscrape, task_id=google_drive_upload, execution_date=20230307T234742, start_date=20230307T235425, end_date=20230307T235556
[2023-03-07T23:55:56.684+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 180 for task google_drive_upload (Command '['/tmp/venv16ee26te/bin/python', '/tmp/venv16ee26te/script.py', '/tmp/venv16ee26te/script.in', '/tmp/venv16ee26te/script.out', '/tmp/venv16ee26te/string_args.txt']' returned non-zero exit status 1.; 703)
[2023-03-07T23:55:56.760+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-07T23:55:56.876+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
